SET client_encoding = 'UTF8';

create TYPE cmp.awx_template_type AS ENUM ('template', 'workflow');
create table cmp.action (
    "id" bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "version" BIGINT DEFAULT 0,
    "created_at" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP(3),
    "updated_at" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP(3),
    "snow_id" BIGINT NOT NULL,
    "awx_id" BIGINT NOT NULL,
    "identifier" VARCHAR(20) NOT NULL UNIQUE,
    "title" VARCHAR(255),
    "description" TEXT,
    "comment" TEXT,
    "error_title" VARCHAR(255),
    "error_description" TEXT,
    "enabled" BOOLEAN NOT NULL DEFAULT FALSE,
    "quickdiscovery" BOOLEAN NOT NULL DEFAULT FALSE,
    "server_installation" BOOLEAN NOT NULL DEFAULT FALSE,
    "change_required" BOOLEAN NOT NULL DEFAULT TRUE,
    "change_type" VARCHAR(20),
    "change_template" VARCHAR(64),
    "change_title" VARCHAR(255),
    "change_description" TEXT,
    "change_error_title" VARCHAR(255),
    "change_error_description" TEXT,
    "awx_job_enabled" BOOLEAN NOT NULL DEFAULT TRUE,
    "awx_template_type" cmp.awx_template_type NOT NULL,
    "awx_template_id" INTEGER,
    "awx_inventory_id" INTEGER,
    "awx_credentials" VARCHAR(50),
    "awx_job_type" VARCHAR(50),
    "awx_limit" VARCHAR(50),
    "awx_job_tags" VARCHAR(50),
    "awx_skip_tags" VARCHAR(50),
    "awx_extra_vars" VARCHAR(250),
    "awx_scm_branch" VARCHAR(50),
    "awx_verbosity" INTEGER,
    "awx_timeout" INTEGER,
    "awx_forks" INTEGER,
    "awx_job_slice_count" INTEGER,
    "awx_execution_environment" INTEGER,
    "awx_instance_groups" VARCHAR(50),
    "awx_labels" VARCHAR(50),
    "awx_estimated_runtime" INTEGER,
    "awx_title" VARCHAR(255),
    "awx_description" TEXT,
    "awx_error_title" VARCHAR(255),
    "awx_error_description" TEXT,
    CONSTRAINT fk_snow_id FOREIGN KEY ("snow_id") REFERENCES cmp.config_snow("id") ON delete RESTRICT,
    CONSTRAINT fk_awx_id FOREIGN KEY ("awx_id") REFERENCES cmp.config_awx("id") ON delete RESTRICT
);
alter TABLE cmp.action OWNER TO cmp;

create TYPE cmp.job_status AS ENUM ('new', 'waiting_for_approval', 'awx_running', 'waiting_for_quickdiscovery', 'waiting_for_tagging', 'successful', 'failed', 'error', 'canceled');
create TYPE cmp.change_status AS ENUM ('new', 'skipped', 'waiting_for_approval', 'approved', 'rejected', 'failed', 'canceled');
create TYPE cmp.awx_status AS ENUM ('new', 'skipped', 'running', 'successful', 'failed', 'error', 'canceled');
create TYPE cmp.quickdiscovery_status AS ENUM ('new', 'skipped', 'waiting', 'successful', 'failed', 'error', 'canceled');
create TYPE cmp.tagging_status AS ENUM ('new', 'skipped', 'waiting',  'successful', 'failed', 'error', 'canceled');
create table cmp.job (
 "id" bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "version" BIGINT DEFAULT 0,
    "created_at" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP(3),
    "updated_at" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP(3),
    "snow_id" BIGINT NOT NULL,
    "awx_id" BIGINT NOT NULL,
    "user_id" BIGINT NOT NULL,
    "server_id" BIGINT,
    "appservice_id" BIGINT,
    "status" cmp.job_status NOT NULL DEFAULT 'new',
    "action_identifier" VARCHAR(20) NOT NULL UNIQUE,
    "action_title" VARCHAR(255),
    "action_description" TEXT,
    "action_error_title" VARCHAR(255),
    "action_error_description" TEXT,
    "quickdiscovery" BOOLEAN NOT NULL,
    "server_installation" BOOLEAN NOT NULL,
    "change_required" BOOLEAN NOT NULL DEFAULT TRUE,
    "change_type" VARCHAR(20),
    "change_template" VARCHAR(64),
    "change_title" VARCHAR(255),
    "change_description" TEXT,
    "change_error_title" VARCHAR(255),
    "change_error_description" TEXT,
    "change_start_date" TIMESTAMPTZ,
    "change_end_date" TIMESTAMPTZ,
    "change_status" cmp.change_status NOT NULL DEFAULT 'new',
    "awx_job_enabled" BOOLEAN NOT NULL DEFAULT TRUE,
    "awx_template_type" cmp.awx_template_type NOT NULL,
    "awx_template_id" INTEGER,
    "awx_inventory_id" INTEGER,
    "awx_credentials" VARCHAR(50),
    "awx_job_type" VARCHAR(50),
    "awx_limit" VARCHAR(50),
    "awx_job_tags" VARCHAR(50),
    "awx_skip_tags" VARCHAR(50),
    "awx_extra_vars" VARCHAR(250),
    "awx_scm_branch" VARCHAR(50),
    "awx_verbosity" INTEGER,
    "awx_timeout" INTEGER,
    "awx_forks" INTEGER,
    "awx_job_slice_count" INTEGER,
    "awx_execution_environment" INTEGER,
    "awx_instance_groups" VARCHAR(50),
    "awx_labels" VARCHAR(50),
    "awx_estimated_runtime" INTEGER,
    "awx_title" VARCHAR(255),
    "awx_description" TEXT,
    "awx_error_title" VARCHAR(255),
    "awx_error_description" TEXT,
    "awx_variables" TEXT,
    "awx_artifacts" TEXT,
    "awx_status" cmp.awx_status NOT NULL DEFAULT 'new',
    "awx_next_status_check" TIMESTAMPTZ,
    "quickdiscovery_status" quickdiscovery_status NOT NULL DEFAULT 'new',
    "tagging_status"cmp.tagging_status NOT NULL DEFAULT 'new',
    "title" VARCHAR(255),
    "description" TEXT,
    CONSTRAINT fk_snow_id FOREIGN KEY ("snow_id") REFERENCES cmp.config_snow("id") ON delete RESTRICT,
    CONSTRAINT fk_awx_id FOREIGN KEY ("awx_id") REFERENCES cmp.config_awx("id") ON delete RESTRICT,
    CONSTRAINT fk_user_id FOREIGN KEY ("user_id") REFERENCES cmp.user("id") ON delete RESTRICT,
    CONSTRAINT fk_server_id FOREIGN KEY ("server_id") REFERENCES cmp.server("id") ON delete CASCADE,
    CONSTRAINT fk_appservice_id FOREIGN KEY ("appservice_id") REFERENCES cmp.appservice("id") ON delete CASCADE
);
alter TABLE cmp.job OWNER TO cmp;
