SET client_encoding = 'UTF8';

ALTER TABLE cmp.appservice
    ALTER COLUMN name TYPE text,
    ALTER COLUMN number TYPE text,
    ALTER COLUMN sys_id TYPE text,
    ALTER COLUMN used_for TYPE text,
    ALTER COLUMN business_service_numbers TYPE text;

ALTER TABLE cmp.server
    ALTER COLUMN uuid TYPE text,
    ALTER COLUMN instance_uuid TYPE text,
    ALTER COLUMN vm_id TYPE text,
    ALTER COLUMN cluster TYPE text,
    ALTER COLUMN host TYPE text,
    ALTER COLUMN location TYPE text,
    ALTER COLUMN name TYPE text,
    ALTER COLUMN power_state TYPE text,
    ALTER COLUMN cpu_topology TYPE text,
    ALTER COLUMN vmx_version TYPE text,
    ALTER COLUMN guest_config_id TYPE text,
    ALTER COLUMN guest_config_full_name TYPE text,
    ALTER COLUMN guest_tools_id TYPE text,
    ALTER COLUMN guest_tools_full_name TYPE text,
    ALTER COLUMN guest_tools_state TYPE text,
    ALTER COLUMN guest_tools_running_status TYPE text,
    ALTER COLUMN guest_tools_version_status TYPE text,
    ALTER COLUMN guest_tools_version_status2 TYPE text,
    ALTER COLUMN guest_tools_install_type TYPE text,
    ALTER COLUMN guest_tools_version TYPE text,
    ALTER COLUMN guest_tools_family TYPE text,
    ALTER COLUMN guest_tools_hostname TYPE text,
    ALTER COLUMN guest_tools_ip_address TYPE text,
    ALTER COLUMN guest_tools_architecture TYPE text,
    ALTER COLUMN guest_tools_bitness TYPE text,
    ALTER COLUMN guest_tools_build_number TYPE text,
    ALTER COLUMN guest_tools_cpe_string TYPE text,
    ALTER COLUMN guest_tools_distro_addl_version TYPE text,
    ALTER COLUMN guest_tools_distro_name TYPE text,
    ALTER COLUMN guest_tools_distro_version TYPE text,
    ALTER COLUMN guest_tools_family_name TYPE text,
    ALTER COLUMN guest_tools_kernel_version TYPE text,
    ALTER COLUMN guest_tools_pretty_name TYPE text,
    ALTER COLUMN server_infos_owner_mail TYPE text,
    ALTER COLUMN server_infos_ticket_no TYPE text,
    ALTER COLUMN fqdn TYPE text,
    ALTER COLUMN foreman_source TYPE text,
    ALTER COLUMN snow_server_name TYPE text,
    ALTER COLUMN snow_server_sys_id TYPE text,
    ALTER COLUMN snow_server_sys_class TYPE text,
    ALTER COLUMN snow_server_hardware_status TYPE text,
    ALTER COLUMN snow_instance_name TYPE text,
    ALTER COLUMN snow_instance_sys_id TYPE text,
    ALTER COLUMN snow_instance_sys_class TYPE text,
    ALTER COLUMN patchnight_group TYPE text,
    ALTER COLUMN patchnight_time TYPE text,
    ALTER COLUMN patchnight_exitstring TYPE text,
    ALTER COLUMN patchnight_change_number TYPE text,
    ALTER COLUMN patchnight_change_sys_id TYPE text,
    ALTER COLUMN operatingsystem TYPE text;

ALTER TABLE cmp.server DROP COLUMN IF EXISTS memory_usage_perc_avg;
ALTER TABLE cmp.server DROP COLUMN IF EXISTS cpu_usage_perc_avg;
