export default class JobList {
  constructor(
    public appServiceId: number,
    public appServiceName: string,
    public awxApiDescription: string,
    public awxError: string,
    public awxJobEnabled: boolean,
    public awxJobId: number,
    public awxJobLink: string,
    public awxStatus: string,
    public awxEndDate: string, // ISO string for Instant
    public awxExtraVars: string,
    public awxStartDate: string, // ISO string for Instant
    public awxTemplateId: number,
    public awxTemplateType: string,
    public awxVariables: string,
    public changeError: string,
    public changeLink: string,
    public changeNumber: string,
    public changeRequired: boolean,
    public changeStartDate: string, // ISO string for Instant
    public changeStatus: string,
    public createdAt: string, // ISO string for Instant
    public description: string,
    public hostname: string,
    public id: number,
    public ip: string,
    public quickdiscovery: boolean,
    public quickdiscoveryCiName: string,
    public quickdiscoveryCiSysid: string,
    public quickdiscoveryError: string,
    public quickdiscoveryErrorCounter: number,
    public quickdiscoveryStatus: string,
    public serverId: number,
    public serverInstallation: boolean,
    public serverName: string,
    public snowApiDescription: string,
    public status: string,
    public taggingError: string,
    public taggingStatus: string,
    public title: string,
    public userName: string,
    public awxJobErrorMessage: string,
    public awxJobArtifacts: string,
    public awxJobOrg: string,
    public awxJobReturnData: string,
    public awxJobReturnMessage: string,
    public awxJobReturnCompleted: boolean,
    public awxJobFailed: boolean,
    public awxJobStatus: string,
    public awxJobDuration: number,
    public awxTemplateLink: string
  ) {}
}