import type { Cloud } from "@/types/Cloud";

export interface AppserviceNameAndSysId {
  id: number;
  name: string;
  sysId: string;
}

export interface ActiveGreenItJob {
  actionTitle: string;
  changeStartDate: string; // ISO string für OffsetDateTime
  changeNumber: string;
  changeLink: string;
}

export default class Server {
  constructor(
    public id: number,
    public cloud: Cloud,
    public uuid: string,
    public instanceUuid: string,
    public vmId: string,
    public cluster: string,
    public host: string,
    public location: string,
    public name: string,
    public powerState: string,
    public memoryMb: number,
    public memoryMbPrev: number,
    public memoryMbChangeDate: string, // ISO string für OffsetDateTime
    public memoryMbRightsizing: string,
    public numCpu: number,
    public numCpuPrev: number,
    public numCpuChangeDate: string, // ISO string für OffsetDateTime
    public numCpuRightsizing: string,
    public numCoresPerSocket: number,
    public memoryHotAddEnabled: boolean,
    public hotPlugMemoryLimit: number,
    public hotPlugMemoryIncrementSize: number,
    public cpuHotAddEnabled: boolean,
    public cpuHotRemoveEnabled: boolean,
    public cpuTopology: string,
    public vmxVersion: string,
    public overallStatus: string,
    public configStatus: string,
    public configEqualsTools: boolean,
    public guestConfigId: string,
    public guestConfigFullName: string,
    public guestToolsId: string,
    public guestToolsFullName: string,
    public guestToolsState: string,
    public guestToolsRunningStatus: string,
    public guestToolsVersionStatus: string,
    public guestToolsVersionStatus2: string,
    public guestToolsInstallType: string,
    public guestToolsVersion: string,
    public guestToolsFamily: string,
    public guestToolsHostname: string,
    public guestToolsIpAddress: string,
    public guestToolsArchitecture: string,
    public guestToolsBitness: string,
    public guestToolsBuildNumber: string,
    public guestToolsCpeString: string,
    public guestToolsDistroAddlVersion: string,
    public guestToolsDistroName: string,
    public guestToolsDistroVersion: string,
    public guestToolsFamilyName: string,
    public guestToolsKernelVersion: string,
    public guestToolsPrettyName: string,
    public vdisks: number,
    public vdisksCapacityInBytes: number,
    public bootTime: string, // ISO string für OffsetDateTime
    public roleLinux: boolean,
    public roleWindows: boolean,
    public roleOracle: boolean,
    public roleNonOracle: boolean,
    public patchnightGroup: string,
    public patchnightTime: string,
    public serverInfosOwnerMail: string,
    public serverInfosTicketNo: string,
    public tetrationAgentInstalled: boolean,
    public managed: boolean,
    public fqdn: string,
    public foremanId: number,
    public foremanSource: string,
    public dbOracle: boolean,
    public dbMariadb: boolean,
    public dbHana: boolean,
    public dbMysql: boolean,
    public dbMssql: boolean,
    public dbPostgres: boolean,
    public dbMongodb: boolean,
    public dbAdabas: boolean,
    public memoryMbRecommended: number,
    public numCpuRecommended: number,
    public snowServerName: string,
    public snowServerSysId: string,
    public snowServerSysClass: string,
    public snowServerHardwareStatus: string,
    public snowServerLastDiscovered: string, // ISO string für OffsetDateTime
    public snowInstanceName: string,
    public snowInstanceSysId: string,
    public snowInstanceSysClass: string,
    public snowInstanceLastDiscovered: string, // ISO string für OffsetDateTime
    public patchnightIncluded: boolean,
    public patchnightEnvironment: string,
    public patchnightStartDate: string, // ISO string für OffsetDateTime
    public patchnightEndDate: string, // ISO string für OffsetDateTime
    public patchnightExitcode: number,
    public patchnightExitcodeChangeDate: string, // ISO string für OffsetDateTime
    public patchnightExitstring: string,
    public patchnightChangeNumber: string,
    public patchnightChangeSysId: string,
    public locked: boolean,
    public canEdit: boolean,
    public appservices: AppserviceNameAndSysId[],
    public maintenanceMode: boolean,
    public maintenanceModeExpiresAt: string,
    public hasTempAdminPrivileges: boolean,
    public hasTempRootPrivileges: boolean,
    public tempPrivilegesExpiresAt: string,
    public runningJobsCount: number,
    public runningGreenItCount: number,
    public numberOfAssignedAppservices: number,
    public operatingsystem: string,
    public activeGreenItJobs: ActiveGreenItJob[],
    public serverKind: string,
    public serverType: string,
    public greenItShutdownChangePending: boolean,
    public greenItShutdownChangeRejectedDate: string,
    public greenItRightsizingChangePending: boolean,
    public greenItRightsizingChangeRejectedDate: string,
    public dn: string,
    public association: string,
    public memorySpeed: number,
    public memoryMbAvailable: number,
    public mfgTime: string,
    public model: string,
    public numOfAdaptors: number,
    public numOfCoresEnabled: number,
    public numOfEthHostIfs: number,
    public numOfFcHostIfs: number,
    public operState: string,
    public ucsmChassisId: number,
    public ucsmChassisSlotId: number,
    public ucsmServerId: number,
    public vendor: string,
    public vid: string,
    public os: string,
    public serverCustomAttributes: Record<string, string>,
    public cpuUtil: number,
    public memUsedPercent: number,
    public memoryAllocationExpandableReservation: boolean,
    public cpuAllocationExpandableReservation: boolean
  ) {}
}
