appender=com.p6spy.engine.spy.appender.Slf4JLogger
logMessageFormat=com.p6spy.engine.spy.appender.CustomLineFormat
customLogMessageFormat=%(currentTime) | %(executionTime) ms | %(category) | SQL | \n%(sql)
dateformat=HH:mm:ss.SSS
sqlformat=true
filter=false
includecategories=statement,prepared,batch,commit,rollback
excludecategories=resultset,result
logfile=