package source

import (
	"fmt"

	"git.muenchen.de/mcmp/webanwendung/mcmp-eai-common/pkg/datasource"
	"git.muenchen.de/mcmp/webanwendung/mcmp-eai-common/pkg/logging"
	"git.muenchen.de/mcmp/webanwendung/mcmp-eai-rightsizing/pkg/client/mcmp"
	"git.muenchen.de/mcmp/webanwendung/mcmp-eai-rightsizing/pkg/processor"
)

const exportFilePattern = "rightsizing_export_%s.json"

// RightsizingSource is a specialized JSON file data source for rightsizing recommendations.
//
// RightsizingSource is a type alias that extends datasource.JsonFileSource to handle
// rightsizing-specific data structures. It implements the app.DataSource interface and is
// responsible for:
//
//   - Fetching rightsizing data through the ComputeRightsizing method
//   - Marshaling the data to JSON format
//   - Writing the JSON output to a file with a hostname-specific filename
//   - Sending the results to the MCMP API for persistence and further processing
//
// The generic type parameter [*mcmp.Rightsizing] specifies that this data source
// handles batches of rightsizing recommendations for multiple servers.
//
// Usage:
//
//	source := source.NewRightsizingSource(
//	    "mcmp",
//	    true,
//	    processor,
//	    mcmpClient,
//	    "https://api.example.com/rightsizing",
//	    logger,
//	)
//
// See datasource.JsonFileSource for the underlying implementation and interface methods.
type RightsizingSource = datasource.JsonFileSource[*mcmp.Rightsizing]

// NewRightsizingSource creates and initializes a new RightsizingSource instance for processing
// and exporting rightsizing recommendations.
//
// NewRightsizingSource is a factory function that constructs a properly configured
// RightsizingSource data source. It combines the processor for computing rightsizing
// recommendations with the MCMP client for API communication and file export capabilities.
//
// The function performs the following operations:
//   - Creates a new RightsizingSource instance
//   - Configures the hostname identifier for logging and file naming
//   - Sets the enabled flag to control whether this source is active
//   - Generates an export filename using the provided hostname
//   - Associates the data processor for fetching rightsizing data
//   - Configures the MCMP client for API communication
//   - Sets the API endpoint for sending results
//   - Attaches the logger for operational logging
//
// Parameters:
//   - hostname: Identifier for this data source (used in logging and filename generation).
//     Example: "mcmp", "production", "datacenter-1"
//   - enabled: Boolean flag indicating whether this data source should actively process data.
//     Set to false to temporarily disable processing without removing the source
//   - dataProcessor: Pointer to a Processor instance responsible for computing rightsizing
//     recommendations. Must not be nil and must have ComputeRightsizing method properly
//     initialized
//   - mcmpClient: Pointer to an mcmp.Client instance for communicating with the MCMP API.
//     Used to send computed recommendations back to the MCMP system for storage and further
//     processing. Must implement the JSONSender interface
//   - apiEndpoint: Full URL of the MCMP API endpoint where rightsizing results will be sent.
//     Example: "https://mcmp.example.com/api/v1/rightsizing"
//   - logger: Logger instance for operational logging and error reporting. Captures all
//     activities related to data fetching, marshaling, file writing, and API communication
//
// Returns:
//   - *RightsizingSource: Fully initialized RightsizingSource instance ready for use in
//     the EAI framework. The returned source implements the app.DataSource interface
//
// The export filename is automatically generated by combining the provided hostname with
// a standardized pattern. For hostname "mcmp", the resulting filename would be:
// "rightsizing_export_mcmp.json"
//
// Example usage in application initialization:
//
//	processor, err := processor.NewProcessor(mcmpClient, logger, config.PROCESSOR)
//	if err != nil {
//	    return fmt.Errorf("failed to create processor: %w", err)
//	}
//
//	source := source.NewRightsizingSource(
//	    "mcmp",                        // Hostname identifier
//	    true,                          // Enabled
//	    processor,                     // Data processor
//	    mcmpClient,                    // MCMP API client
//	    config.MCMP.RightsizingEndpoint, // API endpoint URL
//	    logger,                        // Logger instance
//	)
//
//	sources := []app.DataSource[*mcmp.Rightsizing]{source}
//	if err := app.RunEAI(ctx, config, sources, logger); err != nil {
//	    return fmt.Errorf("failed to run EAI: %w", err)
//	}
//
// See also:
//   - datasource.JsonFileSource: The underlying generic implementation
//   - processor.Processor: The data processor for computing recommendations
//   - mcmp.Client: The MCMP API client for sending results
func NewRightsizingSource(
	hostname string,
	enabled bool,
	dataProcessor *processor.Processor,
	mcmpClient *mcmp.Client,
	apiEndpoint string,
	logger logging.Logger,
) *RightsizingSource {
	return &RightsizingSource{
		Hostname:       hostname,
		Enabled:        enabled,
		ExportFilename: fmt.Sprintf(exportFilePattern, hostname),
		Logger:         logger,
		McmpClient:     mcmpClient,
		ApiEndpoint:    apiEndpoint,
		Fetcher:        dataProcessor.ComputeRightsizing,
	}
}
