package de.muenchen.mcmp.types;

public enum ChangeStatus {
    NEW,
    SKIPPED,
    WAITING_FOR_APPROVAL,
    APPROVED,
    REJECTED,
    FAILED,
    CANCELED,
    WAITING_FOR_SERVICE_NOW_ENABLEMENT,
    WAITING_FOR_SERVICE_NOW_CONFIGURATION,
    WAITING_FOR_INCIDENT_RESOLUTION,
    INCIDENT_FAILED
}
