package de.muenchen.mcmp.types;

public enum JobStatus {
    NEW,
    WAITING_FOR_APPROVAL,
    APPROVED,
    AWX_RUNNING,
    AWX_COMPLETED,
    WAITING_FOR_QUICKDISCOVERY,
    QUICKDISCOVERY_COMPLETED,
    WAITING_FOR_TAGGING,
    TAGGING_COMPLETED,
    SUCCESSFUL,
    FAILED,
    ERROR,
    CANCELED,
    REJECTED,
    WAITING_FOR_AWX_ENABLEMENT,
    WAITING_FOR_AWX_CONFIGURATION,
    WAITING_FOR_SERVICE_NOW_ENABLEMENT,
    WAITING_FOR_SERVICE_NOW_CONFIGURATION,
    QUICKDISCOVERY_FAILED,
    TAGGING_FAILED,
    WAITING_FOR_INCIDENT_RESOLUTION,
    INCIDENT_FAILED
}